### ISSUE TITLE
拔线之后会重新变成选择英雄的界面

### ISSUE THREAD

**Issue by Frankklk** [hbt-org/hearthstone-battlegrounds-tools#16]
![image](https://user-images.githubusercontent.com/44097708/106080975-122c3900-6153-11eb-9de6-74db57977364.png)

**Comment by chenyueban** [comment]
hi~ 目前插件的数据源是依赖解析炉石的日志，拔线之后会导致日志出现一些不太可靠的数据，所以不太好解决。
目前正在打算通过 addon 的形式去读炉石内存，如果成功就能够解决掉这个问题，所以抱歉在此之前只能先这样啦~
