### ISSUE TITLE
会考虑出手机版的吗。。。

### ISSUE THREAD

**Issue by kaixinbaba** [hbt-org/hearthstone-battlegrounds-tools#17]
我一般在手机上玩，我觉得我非常需要拔线。。。其他倒是次要的。。

**Comment by chenyueban** [comment]
目前的第一目标是将 PC 端做好，手机版限制比较多并且我也不太确定能否实现PC现有的这些功能。具体情况还要待定，如果以后有时间会认真考虑手机版
