### ISSUE TITLE
好奇这类插件的实现机制

### ISSUE THREAD

**Issue by showthesunli** [hbt-org/hearthstone-battlegrounds-tools#8]
请问，炉石数据怎么读取？读内存？大数据统计信息来源是那里？ 有api吗？能简单介绍下吗，挺好奇的。

**Comment by chenyueban** [comment]
读取炉石的日志，炉石会将游戏内的操作以日志的形式储存，插件通过实时读取日志并分析得到数据

**Comment by showthesunli** [comment]
@chenyueban 谢谢
